import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })
import dynamic from 'next/dynamic'
const  JolPlayer  = dynamic(
    () => import('jol-player'),
    { ssr: false }
)
  
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <JolPlayer
        option={{
          videoSrc:"/video1.mp4",
          width: 750,
              height: 420,
              language: "en",
              isShowScreenshot: false,
              quality: [{name:'SD',url:""} , {name:'HD',url:"/video1.mp4"} , {name:'FHD',url:""} , {name: 'BD',url:""}]
        }}
      />
      </main>
    </>
  )
}
